#!/bin/sh

if ! [ -e ".done" ]; then
	echo "Run 'do' first"
	exit 1
fi

if [ `id -u` -ne 0 ]; then
	echo "Current user is not root"
	exit 1
fi

mkdir -p /usr/lib

if [ $? -ne 0 ]; then
	echo "Failed to create /usr/lib"
	exit 1
fi

mkdir -p /usr/include/fsma/

if [ $? -ne 0 ]; then
	echo "Failed to create /usr/include/fsma"
	exit 1
fi

cp src/*.so /usr/lib/

if [ $? -ne 0 ]; then
	echo "Failed to copy src/libfsma.so to /usr/lib"
	exit 1;
fi

cp include/*.h /usr/include/fsma/

if [ $? -ne 0 ]; then
	echo "Failed to copy include/*.h to /usr/include/fsma"
	exit 1;
fi

if [ ! -z `which ldconfig` ]; then
	ldconfig

	if [ $? -ne 0 ]; then
		echo "Failed to execute ldconfig"
		exit 1;
	fi
fi

echo "Installation complete."

exit 0

